// Description: Error codes for tinyFS functions

// Error codes for libDisk functions
#define FILE_OPEN_ERROR -1
#define FILE_CLOSE_ERROR -2
#define FILE_READ_ERROR -3
#define FILE_WRITE_ERROR -4
#define FILE_SEEK_ERROR -5
#define ERROR_FILE_NAME_TOO_LONG -6
#define ERROR_DISK_NOT_FOUND -7

// Error codes for tinyFS functions
#define ERROR_INVALID_FILE_SYSTEM -8
#define ERROR_NO_FILE_SYSTEM_MOUNTED -9
#define ERROR_MOUNTING_FS -10
#define ERROR_UNMOUNTING_FS -11
#define ERROR_NOT_ENOUGH_FREE_BLOCKS -12
#define ERROR_FILE_NOT_FOUND_IN_OFT -13
#define ERROR_INVALID_FILE_DESCRIPTOR -14
#define ERROR_FILE_NOT_OPEN -15
#define ERROR_FILE_ALREADY_OPEN -16
#define ERROR_FILE_ALREADY_EXISTS -18
#define ERROR_WRITING_DATA_TO_FILE_EXTENT_BLOCK_WRITEFILE -19
#define ERROR_WRITING_DATA_TO_INODE_BLOCK_WRITEFILE -20
#define ERROR_TFS_SEEK_FILE -21
#define ERROR_READ_BYTE -22


// Sucessful return values for libDisk
#define FILE_OPEN_SUCCESS 0
#define FILE_CLOSE_SUCCESS 0
#define FILE_READ_SUCCESS 0
#define FILE_WRITE_SUCCESS 0
#define FILE_SEEK_SUCCESS 0

// Successful return values for tinyFS
#define SUCCESS_TFS_DISK_CREATED 0
#define SUCCESS_TFS_DISK_MOUNTED 0
#define SUCCESS_TFS_DISK_UNMOUNTED 0 
#define SUCCESS_TFS_CLOSE_FILE 0
#define SUCCESS_TFS_WRITE_FILE 0
#define SUCCESS_TFS_DELETE_FILE 0
#define SUCCESS_TFS_READ_FILE 0
#define SUCCESS_TFS_SEEK_FILE 0
#define SUCCESS_TFS_RENAME_FILE 0
#define SUCCESS_TFS_READ_DIR 0
